### ISSUE TITLE
onsubmit - var submit = true??

### ISSUE THREAD

**Issue by arfa2** [yairEO/validator#11]
Thanks for your reply but sorry I wasn't quick enough before you closed it. I am southern hemisphere so big time diff.

Yes, I tested that - put in an alert ``e.preventDefault();  var submit = true; alert('ajax');`` - but clearly fields had not been finalised, ie. there were still form errors.

I guess there are two questions:
1 - is it possible to do remote checking - eg. "email in use" - as each field is tested
2 - submitting complete, validated form data - with ajax to retain page state.

**Comment by arfa2** [comment]
A bit more testing and I see that
`` if( submit ) { this.submit(); alert('form complete'); return false; } ``
is the point of form completion.

So, still looking at the possibility of remote procedural checking for each field.
I am enjoying working with your code. -thanks

**Comment by yairEO** [comment]
please write me an email, this is not the place to ask for personal help. This is Github ticket system, and this is not a ticket. Also, I don't understand what are you trying to do and why can't you use the code in the demo and just change it to do what you desire...
