### ISSUE TITLE
data-validate-length-range not working

### ISSUE THREAD

**Issue by JokerYuva** [yairEO/validator#12]

**Comment by JokerYuva** [comment]
I tried with after removing the " !skip " and it works.

**Comment by yairEO** [comment]
what was that about?

**Comment by PedroRuizHidalgo** [comment]
I need a 5 exact lenght on numbers for a zip code. My input is like: 
<div class="item form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="supp_zipcode"><?=lang('supp_zipcode')?> <span class="required">*</span></label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                          <input id="supp_zipcode" class="form-control col-md-7 col-xs-12" data-validate-length="5" name="supp_zipcode" placeholder="<?=lang('supp_zipcode')?>" required="required" type="number">
                        </div>
                      </div>


and it permits more than five numbers. What reason?

**Comment by mnswaleh** [comment]
I think that person was refering to the validator.js attribute data-validate-lenght-range="2,10" used to validate the range of characters allawed in a textbox
