### ISSUE TITLE
doesn't validate hidden fields

### ISSUE THREAD

**Issue by shihab-92** [yairEO/validator#18]
jquery by default will only validate visible fields but i do have a form which is divided in four tabs but the validation works for  the active tabs only.Is there a way to validate all the elements in all tabs?

**Comment by yairEO** [comment]
yes, I will soon release a version that can support it. 

what are expecting to happen? how should the user know which form fields were invalid if they are in another tab and "invisible" to the user?

right now the validator marks those fields and can add a tooltip next to them as well, and also returns an object with all the invalid fields, which you could print, but it's not so easily understood where those invalid fields are if they are in another tab. 

I think you should use some "next" button or something which will validate each separate tab content with it's own fields and will not allow to continue to the next tab unless all fields are valid.
