### ISSUE TITLE
I'm trying to use into project "https://colorlib.com/polygon/gentelella/" but don't work

### ISSUE THREAD

**Issue by felizardocharles** [yairEO/validator#25]
I'm trying to use into project "https://colorlib.com/polygon/gentelella/" but don't work. This project already use the version "Validator v1.1.0".

**Comment by yairEO** [comment]
How can I help?

**Comment by tiomno** [comment]
The validator works perfectly in this example https://colorlib.com/polygon/gentelella/form_validation.html I'd close this issue due to lack of details and context.
