### ISSUE TITLE
Validate with multiple submit button

### ISSUE THREAD

**Issue by anidotnet** [yairEO/validator#29]
Validator seems to be not working when a form has multiple buttons. The buttons' value is not being posted to server.

```html
<input id="userName" name="userName"  readonly="readonly" required="required" type="text"/>
..
<button type="submit" class="btn btn-primary" name="action" value="cancel">Cancel</button>
<button type="submit" class="btn btn-success" name="action" value="submit">Submit</button>
<button type="submit" class="btn btn-danger" name="action" value="delete">Delete</button>
```

When I click any of the buttons, action value is not being posted as a request parameter, but other input values are (e.g. userName). But when I  remove the validation, button action is being posted..

This is how the validator is initialized

```javascript
function init_validator() {

    if (typeof (validator) === 'undefined') {
        return;
    }
    console.log('init_validator');

    // initialize the validator function
    validator.message.date = 'not a real date';

    // validate a field on "blur" event, a 'select' on 'change' event & a '.reuired' classed multifield on 'keyup':
    $('form')
        .on('blur', 'input[required], input.optional, select.required', validator.checkField)
        .on('change', 'select.required', validator.checkField)
        .on('keypress', 'input[required][pattern]', validator.keypress);

    $('.multi.required').on('keyup blur', 'input', function () {
        validator.checkField.apply($(this).siblings().last()[0]);
    });

    $('form').submit(function (e) {
        e.preventDefault();
        var submit = true;

        // evaluate the form using generic validaing
        if (!validator.checkAll($(this))) {
            submit = false;
        }

        if (submit)
            this.submit();

        return false;
    });

};
```

Could you please tell me what I am doing wrong?

**Comment by yairEO** [comment]
Validator has nothing to do with posing anything, it only validate form fields which can be changed. buttons are not form fields that can be changed by the user, this isn't a problem which is related to this plugin.

can you make a simple test page on jsbin or jsfiddle where I can examine the issue?
make it as simple as possible. 3 buttons in a form with the same validator function.
use [gitraw](https://rawgit.com/) to link needed files from my repo (js)
