### ISSUE TITLE
checkField method return {} for skipped field

### ISSUE THREAD

**Issue by tiomno** [yairEO/validator#35]
On line 411 the validator returns `{}` when it should return `{ valid:true, error:"" }`, right?

```
// if field did not pass filtering or is simply not passed
if( !field )
    return { valid:true, error:"" }
```

**Comment by yairEO** [comment]
can you clarify what do you mean by "skipped field"? what is the flow here

**Comment by tiomno** [comment]
By "skipped field" I mean a field that is not validated because is disabled, for instance.

In line 405 the method **checkField** `return { valid:true, error:"" }`.
I think it should be the same in line 411, it should `return { valid:true, error:"" }` instead of `return {};` for consistency. If I have a code that checks the returned object it will fail if gets an empty object.

**Comment by yairEO** [comment]
yes you are correct. fixing now
