### ISSUE TITLE
Patterns not work without required attribute

### ISSUE THREAD

**Issue by hljuninho** [yairEO/validator#36]
Hi, 

The inputs configured with patterns work perfectly only with required atribute.
If i remove the required attrb the script not return alerts errors.

There're some way to fix this?

thx a lot.

**Comment by yohanesisa** [comment]
Yeah... i deal with the same issue...
need handler if the input not required but if filled (ie. minmax) it has some validation.

But great work
cheers

**Comment by yairEO** [comment]
why would you remove the required attribute? please clarify the situation for me, if you may..

**Comment by Manikantad6** [comment]
hey @yairEO , we have to apply pattern attribute to check whether the user is giving valid input or not even when it is not mandatory.
what if user inputs some invalid text in non mandatory field?
It is ok to leave that field without entering any data but he cannot enter invalid type of text.
