### ISSUE TITLE
input date not working in Firefox

### ISSUE THREAD

**Issue by yongmin1983** [yairEO/validator#37]
<div class="field">
	<label id="" class="col-xs-2 text-right" for="tel">Date：</label>
	<div id="" class="col-xs-7">
		<input type="date" id="date" name="date" placeholder="  电话"  style="width:100%;padding:0 15px;height:30px;" required="required" />
	</div>						
</div>
This is date formate is not loading in firefox but OK in all other browser.

**Comment by yairEO** [comment]
what does this has to do with the validation plugin?

**Comment by yongmin1983** [comment]
Hi, I found it is not your plugin problem, it is due to Firefox is not
support input="date" .

I will close it.

2017-05-24 13:12 GMT+01:00 vsync <notifications@github.com>:

**Comment by yairEO** [comment]
I closed it already. this plugin is about validation of HTML fields, not how they look like
