### ISSUE TITLE
Unique text or email 

### ISSUE THREAD

**Issue by euginepj** [yairEO/validator#38]
Is there any way to check that the email is unique or not? 
A way to check the value via ajax call.

**Comment by yairEO** [comment]
yes. you write the code which sends an AJAX request to the server and the server validates that... 

I did the google for you:
https://stackoverflow.com/questions/17032125/checking-if-email-address-exists-using-ajax-and-php
https://stackoverflow.com/questions/25728467/checking-email-availablity-using-ajax-in-php
