### ISSUE TITLE
linked fields say that they match when one is empty

### ISSUE THREAD

**Issue by tiomno** [yairEO/validator#40]
I the line [https://github.com/yairEO/validator/blob/master/validator.js#L73](https://github.com/yairEO/validator/blob/master/validator.js#L73) should the comparison be:
`if( b !== a ){`
instead of
`if( b != a && a && b ){`
?

if `a` has a value and b is empty or vice-versa the validator will say that the field is valid when it doesn't match with the link's value.

Do you agree?

**Comment by yairEO** [comment]
I agree, I will make the change.
Thanks for reporting.

sorry for the delay, I was on a long vacation
