### ISSUE TITLE
Custom validation in v1.1.0

### ISSUE THREAD

**Issue by dhara15101991** [yairEO/validator#41]
How to add custom validation for perticular field in v1.1.0 version

jquery.validate.js uses 

```
$.validator.addMethod("checktags", function(value,element,params) { //add custom method
       
    });
```
also how to alter validation message. You have mentioned that 

> Example: for a given type ‘date’ field, lets set a custom (general error) message like so:
>     `validator.message['date'] = 'not a real date';` 

but what if i have type is text. Should i use 
`validator.message['text'] = 'insert proper input';` 

Is there any option for this requirement. 
Thanks in advance

**Comment by yairEO** [comment]
what do you mean `$.validator.addMethod` ? the plugin doesn't have such a thing.

and regarding your second question, I will add support for specific fields' error messages

**Comment by dhara15101991** [comment]
Hi @yairEO ,
`
$.validator.addMethod` this is just a example that we can add custom validation. how can we add custom validation for one field in your js.

**Comment by yairEO** [comment]
you have the `pattern` attribute for that, which you use for custom REGEX (example in README).. unless it's something which cannot be defined by regex, then you need to validate it yourself and it is outside the scope of this plugin

**Comment by dhara15101991** [comment]
okk @yairEO . Thanks for your feedback
