### ISSUE TITLE
Reset Validation

### ISSUE THREAD

**Issue by alfredtech** [yairEO/validator#44]
Hi, I'm using your validator to validate my form inside a modal bootstrap. I use the same form for CRUD. but the thing is when i close the modal, the validator didn't reset the validation. it stuck there and when i open the popup for view / update, the validation is still there.

how to reset the validator?

thanks
Jan

**Comment by yairEO** [comment]
Here's an example how to reset the validator on form `reset` event:

    var validator = new FormValidator( document.forms[0] ); // the form element is passed as an argument, but it's not a must, since it can be passed directly in the `reset` method as well

    // on form "reset" event
    document.forms[0].onreset = function(e){
        validator.reset(); 
    };
