### ISSUE TITLE
Lenght Range

### ISSUE THREAD

**Issue by robertocapannelli** [yairEO/validator#46]
data-validate-lengthRange (like the example) doesn't work, I am trying to get the minimum value. I've tried also data-validate-length-range as suggested in documentation but It doesn't work neither.
What about this mismatch? Which Should I use? Other suggestions? Thanks in advance

**Comment by yairEO** [comment]
I will investigate this, hopefully today or in the following days, thank you for informing me

**Comment by yairEO** [comment]
There was a mistake in the README apparently. the custom attribute to set length range is:

    data-validate-length-range="5,15"
