### ISSUE TITLE
Prevent Submit of the Form

### ISSUE THREAD

**Issue by franciscomontiel** [yairEO/validator#47]
Hi! Such a cool validator! 
Im wondering if it is possible to prevent the submitting of the form by default?

I want the validation but have another code which submits the form,
Thanks!
Great work!

**Comment by yairEO** [comment]
Thanks. unfortunately this question is unrelated to this validator.. it's something you need to solve within your own code.. you can post a question on stackoverflow, with all your code and explain the situation there
