### ISSUE TITLE
Ajax validation

### ISSUE THREAD

**Issue by shrikantr-iprogrammer** [yairEO/validator#51]
Is there a builtin way to validate a field based on ajax call to server. For example I need to validate slug field that it does not already exists.
Second if I manually do a ajax call to server, how can I generate a validation error and show a msg accordingly?

**Comment by yairEO** [comment]
You are supposed to run the validation after the Ajax has been completed. there is no relation to AJAX within this code itself. it's only for validation, nothing else.

**Comment by nomentsoa-andrianjatovo** [comment]
The lack of out-of-the-box support for an ajax field validation and a multistep form validation is a real turn-off tbh.

**Comment by yairEO** [comment]
@nomentsoa-andrianjatovo - This package is only enhancing the built-in browser validation, which also has nothing to do with the developer intent. The form does not care where the data is going after it has its submit (Ajax, etc.) and your job, as a developer is to use the validations to **stop** the form from successfully submit if the validations did not pass, just like the [example in the README](https://github.com/yairEO/validator#usage-example---validate-on-submit):

```js
var validator = new FormValidator()

// this function if the callback for your form's submit event:
function onsubmit (e){
    var validatorResult = validator.checkAll(this); // "this" reffers to the currently submitetd form element

	// if form was not valid, do no continue
    if( !validatorResult.valid ) return;
    
    // do ajax here if form is valid
}
```
 
Regarding *"multistep form validation"*, it's up do you do validate each step separately before continuing to the next step. You can run `validator.checkField(inputElement)`. It's all in the README examples.
