### ISSUE TITLE
How to validate both required and email pattern in the same form?

### ISSUE THREAD

**Issue by ySales** [yairEO/validator#54]
I probably didn't understand well how things work but, how can i validade both required inputs and email? In my app email is required in some forms but not in others. I'm using:

$('#form').on('blur', 'input[required]', validator.checkField);
$('#form').on('blur', 'email', validator.checkField);

But only got email's warnings(invalid email) when the input is required, like a OR operator and i want it to work like a AND.

**Comment by yairEO** [comment]
I don't understand what `$('#form').on('blur', 'email', validator.checkField);` means, because `email` is not a valid selector, and it's not a tag, so what is it?
