### ISSUE TITLE
Number validation on number input is be routed to empty.

### ISSUE THREAD

**Issue by HiroshiFuu** [yairEO/validator#56]
For the input with type number, if you enter a non numeric value, the error will be shown as empty not the number. I found out the reason is the value of the input will be parsed as empty value.

**Comment by yairEO** [comment]
Apparently browsers consider that to be the correct behavior.
I found a [discussion](https://stackoverflow.com/q/18852244/104380) about it on stackoverflow.

I cannot think of a workaround for this problem (it will only happen in old browsers like IE11 and below (didn't check EDGE)
