### ISSUE TITLE
How to check password and confirm password are equal ?

### ISSUE THREAD

**Issue by jasimismail** [yairEO/validator#57]
I didn't get a clear how to use the validator on checking passwords are equal or not.
I am confused with **data-validate-linked** element, and how to use in the html.

**Comment by yairEO** [comment]
You can do it just like it is done in the demo page:

http://yaireo.github.io/validator/

You link the second input to the first one, by the first's `name` attribute:

    <div class="field">
        <label>
            <span>Password</span>
            <input type="password" name="password" data-validate-length="6,8" required='required'>
        </label>
    </div>
    <div class="field">
        <label>
            <span>Repeat password</span>
            <input type="password" name="password2" data-validate-linked='password' required='required'>
        </label>
    </div>
