### ISSUE TITLE
How to set Required for Dropdown

### ISSUE THREAD

**Issue by Manikantad6** [yairEO/validator#59]
required is not working for dropdown, how to make it work?

**Comment by yairEO** [comment]
There's no such thing as `dropdown`. do you mean `<select>` ? because select does have `required` attribute:

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select: 

> The <select> element has some unique attributes you can use to control it, such as multiple to specify whether multiple options can be selected, and size to specify how many options should be shown at one. It also accepts most of the general form input attributes such as required, disabled, autofocus, etc.
