### ISSUE TITLE
Custom validation

### ISSUE THREAD

**Issue by karpiuMG** [yairEO/validator#61]
Is it possible to integrate my custom validation function to your validator?

I have two inputs:
```html
<input type="email" id="email" name="email" class="rodo_group">
<input type="tel" id="phone_number" name="phone_number" class="rodo_group">
```
I want to check if my form has certain class. If so I want to check if at least one of these inputs are complete and show custom message in case of error.

Something like require_from_group method in jqueryvalidation plugin. https://jqueryvalidation.org/require_from_group-method/

**Comment by yairEO** [comment]
No, you cannot and should not put such extremely custom logic inside validator. 

such logic is only specific to your needs and should be written in your code.

## Example:

```
var validator = new FormValidator();

document.forms[0].addeventListener('submit', function(e){
    var validatorResult = validator.checkAll(this);

    if( !validatorResult )
        return;

    ...do your custom validations here...
};
```
