### ISSUE TITLE
data-validate-words can't work with other attribute like data-validate-length

### ISSUE THREAD

**Issue by gcc-tan** [yairEO/validator#62]
When data-validate-words judgment is passed, no other judgment will be made. So if we define multiple attributes that contain data-validate-words, then others  will take no effect.
```
if( data.validateWords ){
    ...
   return true;
}
...
```
Above is a fragment of the code.

Beside in READEME.md, Classes section
```
var validatorClasses = {
    //should change to 
    //item: 'field'
    field : 'field', // class for each input wrapper
    alert : 'alert', // call on the alert tooltip
    bad   : 'bad'    // classes for bad input
};
//should change to 
//validator = new FormValidator({classes:validatorClasses}, null);
validator = new FormValidator(null, {classes:validatorClasses});
```

**Comment by yairEO** [comment]
I did this intentionally because I did not see any use-case for validating the length if you wish to validate word count. 

It will be very confusing if both work at the same time, because an implementor wouldn't be certain if the length is taking into consideration all the words combined, or is it per-word.

What is your specific desired use-case?

**Comment by gcc-tan** [comment]
Thanks for answering my questions. I am using the Gentelella project. This project used your validator to check form elements. I saw the project used like this:
```
<input id="name" class="form-control col-md-7 col-xs-12" data-validate-length-range="1" data-validate-words="3" name="name" placeholder="both name(s) e.g Jon Doe" required="required" type="text">
``` 
I am confused about the output, so I made an issue. But what you said does make sense.

Is there a mistake in the README.md?------Classes section-----sample code

**Comment by yairEO** [comment]
Well, I've just checked and this "Gentelella project" is using a version of my Validator from 3 years ago. I will write them regarding this.
