### ISSUE TITLE
Regex validator does not work on non-required fields

### ISSUE THREAD

**Issue by Aresius423** [yairEO/validator#63]
As the title says - unless required is set, the validator does not seem to care about checking the field.

Editing the HTML5 Regex field on the http://yaireo.github.io/validator/ page and removing the required tag will reproduce this issue.

edit: I just checked - none of the validators work on non-required fields.

**Comment by yairEO** [comment]
you can apply "optional", as the README explains:

https://github.com/yairEO/validator#optional-fields
