### ISSUE TITLE
How to validate input of type email with attribute 'multiple'

### ISSUE THREAD

**Issue by bhaidar** [yairEO/validator#68]
Hello
The input field of type 'email' allows entering multiple emails by adding the 'multiple' attribute.

Is this supported by this library? 

https://developer.mozilla.org/en-US/docs/Learn/Forms/HTML5_input_types#e-mail_address_field

Thanks
Bilal

**Comment by yairEO** [comment]
No it is not, but I am willing to put the work to include support.

I haven't been actively working on this library for years and although I think it is very lightweight and does the job great, it barely gained any traction which a bit of a let down as I had spent at a lot of hours on it.

I believe the change you are requesting wouldn't take long to do, I will try to get to it today or tomorrow

**Comment by yairEO** [comment]
done, please use `v3.3.9` and up
