### ISSUE TITLE
Specific error message per field

### ISSUE THREAD

**Issue by pablogiralt** [yairEO/validator#69]
Hi, I am being able to set a custom message for all the checkbox fields in my form like explained in the docs:

```
const validator = new FormValidator({
      texts : {
        checked: 'You must accept this to submit the form'
      }
    });
```

Now, I would need to be able to set a different message to one of the checkboxes.  The docs read the following:

> This object can be extended easily. The idea is to extend it with new keys which represent the name of the field you want the message to be linked to, and that custom message appear as the general error one

So what I understand by that is that I could add the name property of the field to the texts object to get a custom message, so I tried the following

`<input type="checkbox" name="privacy" required>`

```
const validator = new FormValidator({
      texts : {
        privacy: 'You must accept the privacy policy',
        checked: 'You must accept this to submit the form'
      }
    });
```

But this does not seem to show a custom message for my privacy checkbox.

Is this possible somehow?

**Comment by EKanadily** [comment]
not only that but the library should be able to display custom message per reason why the user input was not valid.

e.g. if a text input is required and the length of the text should be more than 5 characters , the user should recieve error message " please enter somehting" if he didn't enter any text , but the user should recieve "please enter at least 5 characters" if he typed 1 to 4 characters text.

**Comment by pablogiralt** [comment]
@yairEO any possibility you would add support for this?

**Comment by yairEO** [comment]
Done, please see updates documentation with examples
