### ISSUE TITLE
Can this work with different form/input structure

### ISSUE THREAD

**Issue by fluxxus** [yairEO/validator#75]
Hey, maybe I am missing something obvious, but I am having trouble using your library with my `HTML` structure. 

Here is what I got: 

```
                <div class="form-field">
                  <label for="starname">Star Name</label>
                  <div class="form-input">
                    <input type="text" id="starname" placeholder="e.g. Mark and Sarah" required="required">
                    <svg class="gradient-frame">
                      <use href="#border" /></svg>
                  </div>
                  <span id="starname-error" class="error-message"></span>
                </div>
```

I would like to have `bad` class on `form-field` element, instead of the `input`(i get the bad class just on the input itself).

Tried this but no luck: 
`validator.settings.classes.field = 'form-field';`

**Comment by yairEO** [comment]
When you initialize the validator, set its settings: (as [mentioned in the docs](https://github.com/yairEO/validator#classes))

```js
{
	  classes : {
	      item  : 'field',   <------ set this to "form-field"
	      alert : 'alert',
	      bad   : 'bad'
	  }
}
```
