### ISSUE TITLE
How to validate a Select2?

### ISSUE THREAD

**Issue by sebasira** [yairEO/validator#77]
I have a problem when using Select2. When the "bad" class is applied, there's no red-border applied to the select tag. I think it has to be with the inner classes of the Select2, that has a lot of **!important** but I do not know how to solve it

I also think that this could help [Styling jQuery Validation with Select2 4.0 and Bootstrap 3+](https://stackoverflow.com/questions/30783019/styling-jquery-validation-with-select2-4-0-and-bootstrap-3) but I do not know how to apply it.

I've also try with [select2-bootstrap-theme](https://github.com/select2/select2-bootstrap-theme) but still the same.

I hope you could help me! Thank you!

### UPDATE
I've managed to workaround the issue by modifying the style, by adding the selector **.bad span.select2**, like this:

```css
.bad input,
.bad select,
.bad textarea,
.bad span.select2{
```

But it's kind of ugly

**Comment by yairEO** [comment]
Hi, the documentation has a section mentioning how to change the default class names

https://github.com/yairEO/validator#classes

just make sure your CSS selectors match the new `bad` classname

**Comment by sebasira** [comment]
Thanks! I did not realize I can use that feature to solve my problem!
